### PR TITLE
Fix avatar

### LINKED ISSUE #4: Avatars not appearing
Title says it all. The avatars aren't appearing, I've tried changing avatars, using different ones, etc.,

I see my friend's gun, but not his avatar. Interestingly, the "avatar change" thing appears in the log.

Any help would be appreciated.

### PR DESCRIPTION
**Pull request by zurgeg**
Closes #4

### CODE REVIEW

**Comment by notnotnotswipez** [comment]
Your fork is very outdated and reverts many new changes haha

**Comment by zurgeg** [comment]
> Your fork is very outdated and reverts many new changes haha

Whoops, those weren't working on my end, lemme go fix that lol

**Comment by zurgeg** [comment]
> Your fork is very outdated and reverts many new changes haha

Alright, problems fixed.

**Comment by zurgeg** [comment]
By the way @notnotnotswipez, any idea why the avatars are stuck T-posing? I'm wondering if it relates to this change.

**Comment by notnotnotswipez** [comment]
Im currently working on a large refactor of the mod, which will fix these issues. These changes havent been pushed to github yet however, so im not going to merge this. Apologies

**Comment by notnotnotswipez** [comment]
Avatars would get stuck tposing if the bone indexes were never populated on either the client or the rep

**Comment by zurgeg** [comment]
> Im currently working on a large refactor of the mod, which will fix these issues. These changes havent been pushed to github yet however, so im not going to merge this. Apologies

All good, thanks for taking a look!

**Pull request closed without merging**
